//! Build RFC 5322 message bytes from a composed [`Draft`] (S4.2). Turns the user's fields into the
//! wire bytes that [`crate::smtp::send`] delivers. `Date` and `Message-ID` are auto-generated by
//! `mail-builder` when absent. Header addresses carry display names; the SMTP envelope uses the bare
//! addresses separately ([`recipients`] + the from address → [`crate::smtp::envelope`]).

use mail_builder::headers::address::Address;
use mail_builder::MessageBuilder;

/// A message being composed.
#[derive(Clone, Debug, Default)]
pub struct Draft {
    pub from_name: Option<String>,
    pub from_addr: String,
    pub to: Vec<String>,
    pub cc: Vec<String>,
    pub subject: String,
    pub body_text: String,
}

/// Build the RFC 5322 bytes for `draft`, or a calm error if it's missing a sender/recipient.
pub fn build(draft: &Draft) -> Result<Vec<u8>, String> {
    if draft.from_addr.trim().is_empty() {
        return Err("The message needs a sender address.".to_owned());
    }
    if draft.to.is_empty() && draft.cc.is_empty() {
        return Err("Add at least one recipient.".to_owned());
    }

    let mut builder = MessageBuilder::new();
    builder = match draft
        .from_name
        .as_deref()
        .map(str::trim)
        .filter(|n| !n.is_empty())
    {
        Some(name) => builder.from((name, draft.from_addr.as_str())),
        None => builder.from(draft.from_addr.as_str()),
    };
    builder = builder.to(addresses(&draft.to));
    if !draft.cc.is_empty() {
        builder = builder.cc(addresses(&draft.cc));
    }
    builder = builder
        .subject(draft.subject.as_str())
        .text_body(draft.body_text.as_str());

    builder
        .write_to_vec()
        .map_err(|_| "Couldn't build the message.".to_owned())
}

/// Every recipient (To + Cc) as a bare address — for the SMTP envelope (`smtp::envelope`).
pub fn recipients(draft: &Draft) -> Vec<String> {
    draft.to.iter().chain(draft.cc.iter()).cloned().collect()
}

fn addresses(addrs: &[String]) -> Vec<Address<'_>> {
    addrs.iter().map(|a| Address::from(a.as_str())).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Draft {
        Draft {
            from_name: Some("Alice".into()),
            from_addr: "alice@test.local".into(),
            to: vec!["bob@test.local".into()],
            cc: vec!["carol@test.local".into()],
            subject: "Hi".into(),
            body_text: "Hello Bob.".into(),
        }
    }

    #[test]
    fn builds_a_well_formed_message() {
        let bytes = build(&sample()).unwrap();
        let s = String::from_utf8(bytes).unwrap();
        assert!(s.contains("From:") && s.contains("alice@test.local"), "{s}");
        assert!(s.contains("Alice"), "display name in From: {s}");
        assert!(s.contains("To:") && s.contains("bob@test.local"), "{s}");
        assert!(s.contains("Cc:") && s.contains("carol@test.local"), "{s}");
        assert!(s.contains("Subject: Hi"), "{s}");
        assert!(s.contains("Hello Bob."), "{s}");
        // mail-builder auto-fills the RFC-required headers
        assert!(s.contains("Date:"), "auto Date: {s}");
        assert!(s.contains("Message-ID:"), "auto Message-ID: {s}");
    }

    #[test]
    fn round_trips_through_the_parser() {
        let bytes = build(&sample()).unwrap();
        let msg = mail_parser::MessageParser::default().parse(&bytes).unwrap();
        assert_eq!(msg.subject(), Some("Hi"));
        assert!(msg.body_text(0).is_some_and(|b| b.contains("Hello Bob.")));
    }

    #[test]
    fn rejects_missing_sender_or_recipients() {
        let mut d = sample();
        d.from_addr = "  ".into();
        assert!(build(&d).is_err());
        let mut d = sample();
        d.to.clear();
        d.cc.clear();
        assert!(build(&d).is_err());
    }

    #[test]
    fn builds_with_only_to_or_only_cc() {
        let mut to_only = sample();
        to_only.cc.clear();
        assert!(build(&to_only).is_ok(), "a To-only message should build");
        let mut cc_only = sample();
        cc_only.to.clear();
        assert!(build(&cc_only).is_ok(), "a Cc-only message should build");
    }

    #[test]
    fn recipients_combines_to_and_cc() {
        assert_eq!(
            recipients(&sample()),
            vec!["bob@test.local".to_owned(), "carol@test.local".to_owned()]
        );
    }
}
