//! Build RFC 5322 message bytes from a composed [`Draft`] (S4.2). Turns the user's fields into the
//! wire bytes that [`crate::smtp::send`] delivers. `Date` and `Message-ID` are auto-generated by
//! `mail-builder` when absent. Header addresses carry display names; the SMTP envelope uses the bare
//! addresses separately ([`recipients`] + the from address → [`crate::smtp::envelope`]).

use mail_builder::headers::address::Address;
use mail_builder::MessageBuilder;

/// A message being composed.
#[derive(Clone, Debug, Default)]
pub struct Draft {
    pub from_name: Option<String>,
    pub from_addr: String,
    pub to: Vec<String>,
    pub cc: Vec<String>,
    pub subject: String,
    pub body_text: String,
    /// `In-Reply-To` (the parent's Message-ID) — set for replies, for conversation threading.
    pub in_reply_to: Option<String>,
    /// `References` chain (oldest → newest) — set for replies.
    pub references: Vec<String>,
    /// Files attached to the message (SEND-4).
    pub attachments: Vec<Attachment>,
    /// Optional HTML alternative (SEND-6). When set, the message is `multipart/alternative`:
    /// `body_text` is the text/plain part and this is the text/html part.
    pub html_body: Option<String>,
}

/// A file attached to an outgoing message.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Attachment {
    pub filename: String,
    pub content_type: String,
    pub data: Vec<u8>,
}

/// The fields of the message being replied to / forwarded that we need to build the new draft.
#[derive(Clone, Debug, Default)]
pub struct Original<'a> {
    pub from_name: Option<&'a str>,
    pub from_addr: &'a str,
    pub subject: &'a str,
    pub date: Option<&'a str>,
    pub message_id: Option<&'a str>,
    pub in_reply_to: Option<&'a str>,
    /// The original To / Cc (comma-joined bare addresses) — used by [`reply_all`].
    pub to: &'a str,
    pub cc: &'a str,
    pub body_text: &'a str,
}

/// Build a **reply** draft (to the original sender). `Re:`-prefixed subject (no doubling), the
/// original quoted with an attribution line, and the threading headers set.
pub fn reply(orig: &Original, from_name: Option<String>, from_addr: String) -> Draft {
    Draft {
        from_name,
        from_addr,
        to: vec![orig.from_addr.trim().to_owned()],
        cc: Vec::new(),
        subject: prefixed_subject("Re:", orig.subject),
        body_text: quote(orig),
        in_reply_to: orig.message_id.map(str::to_owned),
        references: references_chain(orig),
        attachments: Vec::new(),
        html_body: None,
    }
}

/// Build a **reply-all** draft: To = the original sender + the original `To` (minus your own
/// addresses); Cc = the original `Cc` (minus you and anyone already in To). De-duplicated
/// case-insensitively. Subject/quote/threading match a plain reply.
pub fn reply_all(
    orig: &Original,
    my_addrs: &[String],
    from_name: Option<String>,
    from_addr: String,
) -> Draft {
    let mut draft = reply(orig, from_name, from_addr);
    let is_mine = |a: &str| my_addrs.iter().any(|m| m.eq_ignore_ascii_case(a));
    let mut to = draft.to.clone(); // starts as [original sender]
    for a in split_addrs(orig.to) {
        if !is_mine(&a) && !to.iter().any(|x| x.eq_ignore_ascii_case(&a)) {
            to.push(a);
        }
    }
    let mut cc: Vec<String> = Vec::new();
    for a in split_addrs(orig.cc) {
        if !is_mine(&a)
            && !to.iter().any(|x| x.eq_ignore_ascii_case(&a))
            && !cc.iter().any(|x| x.eq_ignore_ascii_case(&a))
        {
            cc.push(a);
        }
    }
    draft.to = to;
    draft.cc = cc;
    draft
}

/// Split a comma/semicolon-separated address field into trimmed, non-empty addresses.
fn split_addrs(field: &str) -> Vec<String> {
    field
        .split([',', ';'])
        .map(|a| a.trim().to_owned())
        .filter(|a| !a.is_empty())
        .collect()
}

/// Build a **forward** draft. `Fwd:`-prefixed subject and the original included below a header block;
/// recipients are left empty for the person to fill. Forwards start a new thread (no In-Reply-To).
pub fn forward(orig: &Original, from_name: Option<String>, from_addr: String) -> Draft {
    let who = display_from(orig);
    let mut body = String::from("\n\n---------- Forwarded message ----------\n");
    body.push_str(&format!("From: {who}\n"));
    if let Some(date) = orig.date {
        body.push_str(&format!("Date: {date}\n"));
    }
    body.push_str(&format!("Subject: {}\n\n", orig.subject));
    body.push_str(orig.body_text);
    Draft {
        from_name,
        from_addr,
        to: Vec::new(),
        cc: Vec::new(),
        subject: prefixed_subject("Fwd:", orig.subject),
        body_text: body,
        in_reply_to: None,
        references: Vec::new(),
        attachments: Vec::new(),
        html_body: None,
    }
}

/// Add `prefix` (e.g. `Re:`) unless the subject already carries it (case-insensitively; also treats
/// `Fw:` as a forward marker). Empty subjects become just the prefix.
fn prefixed_subject(prefix: &str, subject: &str) -> String {
    let s = subject.trim();
    let lower = s.to_ascii_lowercase();
    let marker = prefix.trim_end_matches(':').to_ascii_lowercase(); // "re" / "fwd"
    let already =
        lower.starts_with(&format!("{marker}:")) || (marker == "fwd" && lower.starts_with("fw:"));
    if already {
        s.to_owned()
    } else if s.is_empty() {
        prefix.trim_end().to_owned()
    } else {
        format!("{prefix} {s}")
    }
}

fn display_from(orig: &Original) -> String {
    match orig.from_name.map(str::trim).filter(|n| !n.is_empty()) {
        Some(name) => format!("{name} <{}>", orig.from_addr.trim()),
        None => orig.from_addr.trim().to_owned(),
    }
}

/// Quote the original body: an attribution line followed by each line prefixed with `> `.
fn quote(orig: &Original) -> String {
    let attribution = match orig.date {
        Some(date) => format!("On {date}, {} wrote:", display_from(orig)),
        None => format!("{} wrote:", display_from(orig)),
    };
    let quoted: String = orig
        .body_text
        .lines()
        .map(|l| {
            if l.is_empty() {
                ">".to_owned()
            } else {
                format!("> {l}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("\n\n{attribution}\n{quoted}")
}

/// The `References` chain for a reply: the original's own References (we keep what we have — its
/// In-Reply-To) followed by the original's Message-ID, de-duplicated in order.
fn references_chain(orig: &Original) -> Vec<String> {
    let mut chain = Vec::new();
    if let Some(parent) = orig.in_reply_to.map(str::trim).filter(|s| !s.is_empty()) {
        chain.push(parent.to_owned());
    }
    if let Some(mid) = orig.message_id.map(str::trim).filter(|s| !s.is_empty()) {
        if !chain.contains(&mid.to_owned()) {
            chain.push(mid.to_owned());
        }
    }
    chain
}

/// Build the RFC 5322 bytes for `draft`, or a calm error if it's missing a sender/recipient.
pub fn build(draft: &Draft) -> Result<Vec<u8>, String> {
    if draft.to.is_empty() && draft.cc.is_empty() {
        return Err("Add at least one recipient.".to_owned());
    }
    build_inner(draft, None)
}

/// Build the RFC 5322 bytes for an **unsent draft** (SEND-5, server-backed drafts): unlike [`build`]
/// it does **not** require recipients — a half-written draft legitimately has none yet — and it
/// stamps `message_id` so the appended server copy can be found again by `HEADER Message-ID` (IMAP's
/// `APPENDUID` isn't surfaced by our client).
pub fn build_draft(draft: &Draft, message_id: &str) -> Result<Vec<u8>, String> {
    build_inner(draft, Some(message_id))
}

fn build_inner(draft: &Draft, message_id: Option<&str>) -> Result<Vec<u8>, String> {
    if draft.from_addr.trim().is_empty() {
        return Err("The message needs a sender address.".to_owned());
    }

    let mut builder = MessageBuilder::new();
    if let Some(mid) = message_id {
        builder = builder.message_id(mid);
    }
    builder = match draft
        .from_name
        .as_deref()
        .map(str::trim)
        .filter(|n| !n.is_empty())
    {
        Some(name) => builder.from((name, draft.from_addr.as_str())),
        None => builder.from(draft.from_addr.as_str()),
    };
    if !draft.to.is_empty() {
        builder = builder.to(addresses(&draft.to));
    }
    if !draft.cc.is_empty() {
        builder = builder.cc(addresses(&draft.cc));
    }
    builder = builder
        .subject(draft.subject.as_str())
        .text_body(draft.body_text.as_str());
    if let Some(html) = draft.html_body.as_deref() {
        builder = builder.html_body(html); // → multipart/alternative with the text part above
    }
    if let Some(irt) = draft.in_reply_to.as_deref().filter(|s| !s.is_empty()) {
        builder = builder.in_reply_to(irt);
    }
    if !draft.references.is_empty() {
        let refs: Vec<&str> = draft.references.iter().map(String::as_str).collect();
        builder = builder.references(refs);
    }
    for a in &draft.attachments {
        builder = builder.attachment(a.content_type.as_str(), a.filename.as_str(), a.data.clone());
    }

    builder
        .write_to_vec()
        .map_err(|_| "Couldn't build the message.".to_owned())
}

/// Render Markdown to an HTML fragment for the text/html alternative (SEND-6) — gives bold, lists,
/// links, etc. from readable plain-text markup. Strikethrough + tables enabled.
pub fn render_markdown(md: &str) -> String {
    let mut opts = pulldown_cmark::Options::empty();
    opts.insert(pulldown_cmark::Options::ENABLE_STRIKETHROUGH);
    opts.insert(pulldown_cmark::Options::ENABLE_TABLES);
    let parser = pulldown_cmark::Parser::new_ext(md, opts);
    let mut html = String::new();
    pulldown_cmark::html::push_html(&mut html, parser);
    html
}

/// Guess a MIME content-type from a filename's extension, falling back to a generic binary type.
pub fn guess_content_type(filename: &str) -> String {
    let ext = filename
        .rsplit('.')
        .next()
        .unwrap_or("")
        .to_ascii_lowercase();
    let ty = match ext.as_str() {
        "txt" | "text" | "log" => "text/plain",
        "html" | "htm" => "text/html",
        "csv" => "text/csv",
        "pdf" => "application/pdf",
        "json" => "application/json",
        "zip" => "application/zip",
        "doc" => "application/msword",
        "docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "xls" => "application/vnd.ms-excel",
        "xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "svg" => "image/svg+xml",
        _ => "application/octet-stream",
    };
    ty.to_owned()
}

/// The signature block to append to a composed body: a blank line, the standard `-- ` delimiter, then
/// the signature. Empty (no delimiter) when the signature is blank.
pub fn signature_block(signature: &str) -> String {
    if signature.trim().is_empty() {
        String::new()
    } else {
        format!("\n\n-- \n{signature}")
    }
}

/// Every recipient (To + Cc) as a bare address — for the SMTP envelope (`smtp::envelope`).
pub fn recipients(draft: &Draft) -> Vec<String> {
    draft.to.iter().chain(draft.cc.iter()).cloned().collect()
}

fn addresses(addrs: &[String]) -> Vec<Address<'_>> {
    addrs.iter().map(|a| Address::from(a.as_str())).collect()
}

/// Build an RFC 822 `.eml` (bytes) from a stored message — its headers + text/HTML bodies — so it can
/// be saved to disk and re-opened (here or in any mail client). Bodies are faithful; headers are
/// reconstructed from what we store (Date from the stored timestamp, Message-ID if present).
pub fn export_eml(
    header: &geleit_store::MessageHeader,
    body: Option<&geleit_store::StoredBody>,
) -> Result<Vec<u8>, String> {
    let mut b = MessageBuilder::new();
    b = match header
        .from_name
        .as_deref()
        .map(str::trim)
        .filter(|n| !n.is_empty())
    {
        Some(name) => b.from((name, header.from_addr.as_deref().unwrap_or(""))),
        None => b.from(header.from_addr.as_deref().unwrap_or("")),
    };
    let to = split_addrs(header.to_addrs.as_deref().unwrap_or(""));
    if !to.is_empty() {
        b = b.to(addresses(&to));
    }
    let cc = split_addrs(header.cc_addrs.as_deref().unwrap_or(""));
    if !cc.is_empty() {
        b = b.cc(addresses(&cc));
    }
    b = b.subject(header.subject.as_deref().unwrap_or("(no subject)"));
    if let Some(mid) = header.message_id.as_deref().filter(|s| !s.is_empty()) {
        b = b.message_id(mid);
    }
    if let Some(ts) = header.date {
        b = b.date(ts);
    }
    let plain = body.and_then(|x| x.plain.as_deref());
    let html = body.and_then(|x| x.html.as_deref());
    b = match (plain, html) {
        (Some(p), Some(h)) => b.text_body(p).html_body(h),
        (Some(p), None) => b.text_body(p),
        (None, Some(h)) => b.html_body(h),
        (None, None) => b.text_body(""),
    };
    b.write_to_vec()
        .map_err(|_| "Couldn't build the .eml file.".to_owned())
}

/// Fields recovered from a `.eml` file when opening one.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct ImportedEml {
    pub subject: Option<String>,
    pub from_name: Option<String>,
    pub from_addr: Option<String>,
    pub to_addrs: Option<String>,
    pub date: Option<i64>,
    pub message_id: Option<String>,
    pub plain: Option<String>,
    pub html: Option<String>,
    pub has_attachments: bool,
}

/// Parse a `.eml` file's bytes into the fields the reading pane needs — headers (RFC 2047-decoded by
/// `mail-parser`) + the text/HTML bodies (via the same `mime` parser used for synced mail). Returns
/// defaults for a file that doesn't parse as a message.
pub fn parse_eml(raw: &[u8]) -> ImportedEml {
    let Some(msg) = mail_parser::MessageParser::default().parse(raw) else {
        return ImportedEml::default();
    };
    let from = msg.from().and_then(|a| a.first());
    let to_addrs = msg.to().map(|a| {
        a.iter()
            .filter_map(|x| x.address())
            .collect::<Vec<_>>()
            .join(", ")
    });
    let body = crate::mime::parse_body(raw);
    ImportedEml {
        subject: msg.subject().map(str::to_owned),
        from_name: from.and_then(|a| a.name()).map(str::to_owned),
        from_addr: from.and_then(|a| a.address()).map(str::to_owned),
        to_addrs: to_addrs.filter(|s| !s.is_empty()),
        date: msg.date().map(|d| d.to_timestamp()),
        message_id: msg.message_id().map(str::to_owned),
        plain: body.plain,
        html: body.html,
        has_attachments: body.has_attachments,
    }
}

/// The compose form recovered from a queued message's raw bytes, so a rejected send can be *edited*
/// (fix a bad address, a typo) rather than discarded and retyped. Mirrors the `ComposeDraft` shape
/// the frontend fills in: recipients split back into To/Cc, the subject, the plaintext body, and each
/// attachment's name + bytes (materialised to temp files by the caller, as draft resume does).
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct OutboxEdit {
    pub to: String,
    pub cc: String,
    pub subject: String,
    pub body: String,
    /// Each attachment as `(filename, bytes)`, in the order the message lists them.
    pub attachments: Vec<(Option<String>, Vec<u8>)>,
}

/// Reconstruct the compose form from a queued message's raw RFC 5322 bytes (SEND-10 edit). We built
/// these bytes ourselves at enqueue time, so parsing is a faithful inverse: To/Cc are the bare
/// recipient addresses (as the composer's fields hold them), the body is the `text/plain` part, and
/// each attachment its name + bytes. Parses the message **once**. Two deliberate lossy points, both
/// matching how resuming a draft behaves: recipient display names are dropped (the compose field and
/// the send path speak bare addresses), and a formatted (Markdown/HTML) message comes back as its
/// plaintext. Threading headers (In-Reply-To/References) are dropped too — an edited-and-resent
/// message starts a fresh send; it isn't a reply to itself.
pub fn parse_outbox_for_edit(raw: &[u8]) -> OutboxEdit {
    use mail_parser::MimeHeaders; // brings `attachment_name` into scope
    let Some(msg) = mail_parser::MessageParser::default().parse(raw) else {
        return OutboxEdit::default();
    };
    let join_addrs = |field: Option<&mail_parser::Address>| {
        field.map_or_else(String::new, |a| {
            a.iter()
                .filter_map(|x| x.address())
                .collect::<Vec<_>>()
                .join(", ")
        })
    };
    let attachments = msg
        .attachments()
        .map(|part| {
            (
                part.attachment_name().map(str::to_owned),
                part.contents().to_vec(),
            )
        })
        .collect();
    OutboxEdit {
        to: join_addrs(msg.to()),
        cc: join_addrs(msg.cc()),
        subject: msg.subject().unwrap_or_default().to_owned(),
        body: msg.body_text(0).map(|c| c.into_owned()).unwrap_or_default(),
        attachments,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_then_parse_eml_roundtrips() {
        use geleit_store::{MessageHeader, StoredBody};
        let header = MessageHeader {
            id: 1,
            uid: None,
            message_id: Some("<m1@example.com>".into()),
            in_reply_to: None,
            subject: Some("Grüße — a saved message".into()), // non-ASCII → exercises RFC2047
            from_name: Some("Anna Müller".into()),
            from_addr: Some("anna@example.com".into()),
            to_addrs: Some("bob@example.com".into()),
            cc_addrs: None,
            date: Some(1_700_000_000),
            seen: true,
            flagged: false,
            has_attachments: false,
            snippet: None,
        };
        let body = StoredBody {
            plain: Some("Plain body text.".into()),
            html: Some("<p>Hi <b>there</b></p>".into()),
        };
        let bytes = export_eml(&header, Some(&body)).expect("export");
        let p = parse_eml(&bytes);
        assert_eq!(p.subject.as_deref(), Some("Grüße — a saved message"));
        assert_eq!(p.from_name.as_deref(), Some("Anna Müller"));
        assert_eq!(p.from_addr.as_deref(), Some("anna@example.com"));
        assert_eq!(p.to_addrs.as_deref(), Some("bob@example.com"));
        assert_eq!(p.plain.as_deref(), Some("Plain body text."));
        assert!(p
            .html
            .as_deref()
            .unwrap_or_default()
            .contains("<b>there</b>"));
    }

    #[test]
    fn parse_eml_handles_garbage() {
        assert_eq!(parse_eml(b"not a message"), ImportedEml::default());
    }

    fn sample() -> Draft {
        Draft {
            from_name: Some("Alice".into()),
            from_addr: "alice@test.local".into(),
            to: vec!["bob@test.local".into()],
            cc: vec!["carol@test.local".into()],
            subject: "Hi".into(),
            body_text: "Hello Bob.".into(),
            ..Default::default()
        }
    }

    #[test]
    fn builds_a_well_formed_message() {
        let bytes = build(&sample()).unwrap();
        let s = String::from_utf8(bytes).unwrap();
        assert!(s.contains("From:") && s.contains("alice@test.local"), "{s}");
        assert!(s.contains("Alice"), "display name in From: {s}");
        assert!(s.contains("To:") && s.contains("bob@test.local"), "{s}");
        assert!(s.contains("Cc:") && s.contains("carol@test.local"), "{s}");
        assert!(s.contains("Subject: Hi"), "{s}");
        assert!(s.contains("Hello Bob."), "{s}");
        // mail-builder auto-fills the RFC-required headers
        assert!(s.contains("Date:"), "auto Date: {s}");
        assert!(s.contains("Message-ID:"), "auto Message-ID: {s}");
    }

    #[test]
    fn attachment_is_included_and_parseable() {
        let mut d = sample();
        d.attachments = vec![Attachment {
            filename: "notes.txt".into(),
            content_type: "text/plain".into(),
            data: b"hello file".to_vec(),
        }];
        use mail_parser::MimeHeaders;
        let bytes = build(&d).unwrap();
        let msg = mail_parser::MessageParser::default().parse(&bytes).unwrap();
        let att = msg.attachments().next().expect("an attachment");
        assert_eq!(att.attachment_name(), Some("notes.txt"));
        assert_eq!(att.contents(), b"hello file");
    }

    #[test]
    fn render_markdown_basic_formatting() {
        let html = render_markdown("**bold** and a [link](http://x.test)\n\n- one\n- two");
        assert!(html.contains("<strong>bold</strong>"), "{html}");
        assert!(
            html.contains("<a href=\"http://x.test\">link</a>"),
            "{html}"
        );
        assert!(
            html.contains("<li>one</li>") && html.contains("<li>two</li>"),
            "{html}"
        );
        // the enabled extensions: strikethrough + tables
        assert!(render_markdown("~~gone~~").contains("<del>gone</del>"));
        assert!(render_markdown("| a | b |\n|---|---|\n| 1 | 2 |").contains("<table>"));
    }

    #[test]
    fn html_body_makes_a_multipart_alternative() {
        let mut d = sample();
        d.body_text = "**hi**".into();
        d.html_body = Some(render_markdown("**hi**"));
        let bytes = build(&d).unwrap();
        let msg = mail_parser::MessageParser::default().parse(&bytes).unwrap();
        assert_eq!(msg.text_body.len(), 1, "a text/plain part");
        assert_eq!(msg.html_body.len(), 1, "a text/html part");
        let html = msg.body_html(0).unwrap();
        assert!(html.contains("<strong>hi</strong>"), "{html}");
    }

    #[test]
    fn round_trips_through_the_parser() {
        let bytes = build(&sample()).unwrap();
        let msg = mail_parser::MessageParser::default().parse(&bytes).unwrap();
        assert_eq!(msg.subject(), Some("Hi"));
        assert!(msg.body_text(0).is_some_and(|b| b.contains("Hello Bob.")));
    }

    #[test]
    fn rejects_missing_sender_or_recipients() {
        let mut d = sample();
        d.from_addr = "  ".into();
        assert!(build(&d).is_err());
        let mut d = sample();
        d.to.clear();
        d.cc.clear();
        assert!(build(&d).is_err());
    }

    #[test]
    fn parse_outbox_for_edit_inverts_build() {
        // A queued message's raw bytes must round-trip back into the compose form the user typed,
        // so "Edit" on a rejected send reopens it faithfully — recipients split To/Cc, body intact,
        // attachment name + bytes recovered.
        let mut d = sample();
        d.to = vec!["bob@test.local".into(), "dave@test.local".into()];
        d.cc = vec!["carol@test.local".into()];
        d.body_text = "Fix the address and resend.".into();
        d.attachments = vec![Attachment {
            filename: "notes.txt".into(),
            content_type: "text/plain".into(),
            data: b"the notes".to_vec(),
        }];
        let raw = build(&d).unwrap();

        let edit = parse_outbox_for_edit(&raw);
        assert_eq!(edit.to, "bob@test.local, dave@test.local");
        assert_eq!(edit.cc, "carol@test.local");
        assert_eq!(edit.subject, "Hi");
        assert_eq!(edit.body, "Fix the address and resend.");
        assert_eq!(
            edit.attachments,
            vec![(Some("notes.txt".to_owned()), b"the notes".to_vec())]
        );
    }

    #[test]
    fn parse_outbox_for_edit_survives_garbage() {
        // Never panic on bytes that don't parse — return an empty form.
        assert_eq!(
            parse_outbox_for_edit(b"\xff not a message"),
            OutboxEdit::default()
        );
    }

    #[test]
    fn builds_with_only_to_or_only_cc() {
        let mut to_only = sample();
        to_only.cc.clear();
        assert!(build(&to_only).is_ok(), "a To-only message should build");
        let mut cc_only = sample();
        cc_only.to.clear();
        assert!(build(&cc_only).is_ok(), "a Cc-only message should build");
    }

    #[test]
    fn build_draft_allows_no_recipients_and_stamps_the_message_id() {
        // A half-written draft has no recipients yet — `build` refuses it, `build_draft` must not.
        let mut empty = sample();
        empty.to.clear();
        empty.cc.clear();
        assert!(
            build(&empty).is_err(),
            "the send path still needs a recipient"
        );
        let mid = "<geleit-draft-1-1700000000@geleit.local>";
        let bytes = build_draft(&empty, mid).expect("a recipient-less draft should build");
        let raw = String::from_utf8_lossy(&bytes);
        // The Message-ID is stamped — it's how the appended server copy is found again.
        assert!(raw.contains(mid), "message-id missing: {raw}");
        // No recipients → no empty To: header to confuse a server.
        assert!(!raw.contains("\r\nTo: \r\n"), "empty To header: {raw}");
        // A sender is still required (we can't append a message from nobody).
        let mut no_from = empty.clone();
        no_from.from_addr = String::new();
        assert!(build_draft(&no_from, mid).is_err());
        // With recipients it behaves like a normal build (plus the Message-ID).
        let with = build_draft(&sample(), mid).expect("build");
        let raw = String::from_utf8_lossy(&with);
        assert!(raw.contains("bob@test.local") && raw.contains(mid));
    }

    #[test]
    fn recipients_combines_to_and_cc() {
        assert_eq!(
            recipients(&sample()),
            vec!["bob@test.local".to_owned(), "carol@test.local".to_owned()]
        );
    }

    fn orig() -> Original<'static> {
        Original {
            from_name: Some("Bob"),
            from_addr: "bob@test.local",
            subject: "Lunch",
            date: Some("Mon, 1 Jun 2026 12:00:00 +0000"),
            message_id: Some("<abc@test.local>"),
            in_reply_to: Some("<parent@test.local>"),
            to: "me@test.local, carol@test.local",
            cc: "dave@test.local",
            body_text: "Are you free?\n\nBob",
        }
    }

    #[test]
    fn reply_targets_sender_prefixes_subject_and_threads() {
        let d = reply(&orig(), Some("Me".into()), "me@test.local".into());
        assert_eq!(d.to, vec!["bob@test.local"]);
        assert_eq!(d.subject, "Re: Lunch");
        assert_eq!(d.in_reply_to.as_deref(), Some("<abc@test.local>"));
        // References = parent's In-Reply-To, then the original's Message-ID
        assert_eq!(
            d.references,
            vec!["<parent@test.local>", "<abc@test.local>"]
        );
        // body is quoted with an attribution line
        assert!(
            d.body_text.contains("Bob <bob@test.local> wrote:"),
            "{}",
            d.body_text
        );
        assert!(d.body_text.contains("> Are you free?"), "{}", d.body_text);
        assert_eq!(d.from_addr, "me@test.local");
    }

    #[test]
    fn reply_all_includes_others_and_excludes_me() {
        let me = vec!["me@test.local".to_owned()];
        let d = reply_all(&orig(), &me, Some("Me".into()), "me@test.local".into());
        // To = sender + original To (minus me, deduped)
        assert_eq!(d.to, vec!["bob@test.local", "carol@test.local"]);
        // Cc = original Cc minus me
        assert_eq!(d.cc, vec!["dave@test.local"]);
        // still threaded + Re:-prefixed like a reply
        assert_eq!(d.subject, "Re: Lunch");
        assert_eq!(d.in_reply_to.as_deref(), Some("<abc@test.local>"));
    }

    #[test]
    fn reply_all_dedups_cc_against_to_and_itself() {
        let o = Original {
            from_addr: "bob@x",
            subject: "S",
            message_id: Some("<m>"),
            to: "alice@x, me@x",
            cc: "alice@x, dave@x, dave@x", // alice is also in To; dave is duplicated
            ..Default::default()
        };
        let me = vec!["me@x".to_owned()];
        let d = reply_all(&o, &me, None, "me@x".into());
        assert_eq!(d.to, vec!["bob@x", "alice@x"]); // sender + To, minus me
                                                    // Cc drops alice (already in To) + the duplicate dave + me
        assert_eq!(d.cc, vec!["dave@x"]);
    }

    #[test]
    fn reply_does_not_double_the_re_prefix() {
        let mut o = orig();
        o.subject = "RE: Lunch";
        assert_eq!(reply(&o, None, "me@x".into()).subject, "RE: Lunch");
    }

    #[test]
    fn forward_prefixes_includes_original_and_has_no_recipients() {
        let d = forward(&orig(), Some("Me".into()), "me@test.local".into());
        assert_eq!(d.subject, "Fwd: Lunch");
        assert!(d.to.is_empty());
        assert!(d.in_reply_to.is_none());
        assert!(d.references.is_empty());
        assert!(d.body_text.contains("Forwarded message"), "{}", d.body_text);
        assert!(
            d.body_text.contains("From: Bob <bob@test.local>"),
            "{}",
            d.body_text
        );
        assert!(d.body_text.contains("Are you free?"), "{}", d.body_text);
        // "Fw:" is also treated as an existing forward marker
        let mut o = orig();
        o.subject = "Fw: Lunch";
        assert_eq!(forward(&o, None, "me@x".into()).subject, "Fw: Lunch");
    }

    #[test]
    fn guess_content_type_by_extension() {
        for (name, ty) in [
            ("a.txt", "text/plain"),
            ("a.text", "text/plain"),
            ("a.log", "text/plain"),
            ("a.html", "text/html"),
            ("a.htm", "text/html"),
            ("a.csv", "text/csv"),
            ("a.PDF", "application/pdf"), // case-insensitive
            ("a.json", "application/json"),
            ("a.zip", "application/zip"),
            ("a.doc", "application/msword"),
            (
                "a.docx",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ),
            ("a.xls", "application/vnd.ms-excel"),
            (
                "a.xlsx",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ),
            ("a.png", "image/png"),
            ("a.jpg", "image/jpeg"),
            ("a.jpeg", "image/jpeg"),
            ("a.gif", "image/gif"),
            ("a.webp", "image/webp"),
            ("a.svg", "image/svg+xml"),
            ("noext", "application/octet-stream"),
            ("a.unknown", "application/octet-stream"),
        ] {
            assert_eq!(guess_content_type(name), ty, "for {name}");
        }
    }

    #[test]
    fn signature_block_uses_standard_delimiter_and_is_empty_when_blank() {
        assert_eq!(signature_block("  "), "");
        assert_eq!(signature_block(""), "");
        assert_eq!(signature_block("Alice"), "\n\n-- \nAlice");
    }

    #[test]
    fn reply_emits_threading_headers_in_built_bytes() {
        let d = reply(&orig(), None, "me@test.local".into());
        let bytes = build(&d).unwrap();
        let s = String::from_utf8(bytes).unwrap();
        assert!(
            s.contains("In-Reply-To:") && s.contains("<abc@test.local>"),
            "{s}"
        );
        assert!(
            s.contains("References:") && s.contains("<parent@test.local>"),
            "{s}"
        );
    }
}
